name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v1

    - name: Set up conda environment with micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-binary-path: ~/.local/bin/micromamba
        environment-file: devtools/conda-envs/proteinbenchmark.yaml
        create-args: >-
          python=${{ matrix.python-version }}

    - name: Install package
      run: |
        python -m pip install . --no-deps
        micromamba list

    - name: Run tests
      run: |
        python -m pytest -v proteinbenchmark/tests/ \
            --cov=proteinbenchmark --cov-report=xml --color=yes

    - name: CodeCov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
